artifact_uri: file:///C:/Users/Administrador/Desktop/CaseT%C3%A9cnico_Aquarela_TimeSeries/models/artifacts/759265987466837568/14637bc37bde4db58aaaf4656c2dcb47/artifacts
end_time: 1754407622488
entry_point_name: ''
experiment_id: '759265987466837568'
lifecycle_stage: active
run_id: 14637bc37bde4db58aaaf4656c2dcb47
run_name: Full ML Pipeline Run
run_uuid: 14637bc37bde4db58aaaf4656c2dcb47
source_name: ''
source_type: 4
source_version: ''
start_time: 1754407212352
status: 3
tags: []
user_id: Administrador
