artifact_uri: file:///C:/Users/Administrador/Desktop/CaseT%C3%A9cnico_Aquarela_TimeSeries/models/artifacts/759265987466837568/0cfbf9cc903f4d029f565eebfdd56dbf/artifacts
end_time: 1754407738914
entry_point_name: ''
experiment_id: '759265987466837568'
lifecycle_stage: active
run_id: 0cfbf9cc903f4d029f565eebfdd56dbf
run_name: Fold_1
run_uuid: 0cfbf9cc903f4d029f565eebfdd56dbf
source_name: ''
source_type: 4
source_version: ''
start_time: 1754407728090
status: 3
tags: []
user_id: Administrador
