artifact_uri: file:///C:/Users/Administrador/Desktop/CaseT%C3%A9cnico_Aquarela_TimeSeries/models/artifacts/759265987466837568/67aae7c0e060453d9bc516d9b08e49fe/artifacts
end_time: 1754409314476
entry_point_name: ''
experiment_id: '759265987466837568'
lifecycle_stage: active
run_id: 67aae7c0e060453d9bc516d9b08e49fe
run_name: Full ML Pipeline Run
run_uuid: 67aae7c0e060453d9bc516d9b08e49fe
source_name: ''
source_type: 4
source_version: ''
start_time: 1754409290871
status: 3
tags: []
user_id: Administrador
