artifact_uri: file:///C:/Users/Administrador/Desktop/CaseT%C3%A9cnico_Aquarela_TimeSeries/models/artifacts/759265987466837568/b47f1a53bce2417eb1e3a718ac72d872/artifacts
end_time: 1754406598781
entry_point_name: ''
experiment_id: '759265987466837568'
lifecycle_stage: active
run_id: b47f1a53bce2417eb1e3a718ac72d872
run_name: Full ML Pipeline Run
run_uuid: b47f1a53bce2417eb1e3a718ac72d872
source_name: ''
source_type: 4
source_version: ''
start_time: 1754406598192
status: 3
tags: []
user_id: Administrador
