artifact_uri: file:///C:/Users/Administrador/Desktop/CaseT%C3%A9cnico_Aquarela_TimeSeries/models/artifacts/759265987466837568/5ea27cdf4d104b589ca24617fbc83ddc/artifacts
end_time: 1754407641032
entry_point_name: ''
experiment_id: '759265987466837568'
lifecycle_stage: active
run_id: 5ea27cdf4d104b589ca24617fbc83ddc
run_name: Full ML Pipeline Run
run_uuid: 5ea27cdf4d104b589ca24617fbc83ddc
source_name: ''
source_type: 4
source_version: ''
start_time: 1754407636751
status: 4
tags: []
user_id: Administrador
