artifact_location: file:///C:/Users/Administrador/Desktop/CaseT%C3%A9cnico_Aquarela_TimeSeries/models/artifacts/759265987466837568
creation_time: 1754406423474
experiment_id: '759265987466837568'
last_update_time: 1754406423474
lifecycle_stage: active
name: Walk-Forward Validation
