artifact_uri: file:///C:/Users/Administrador/Desktop/CaseT%C3%A9cnico_Aquarela_TimeSeries/models/artifacts/759265987466837568/e0ea3e140e0d407186337e7dfa042acf/artifacts
end_time: 1754408076094
entry_point_name: ''
experiment_id: '759265987466837568'
lifecycle_stage: active
run_id: e0ea3e140e0d407186337e7dfa042acf
run_name: Full ML Pipeline Run
run_uuid: e0ea3e140e0d407186337e7dfa042acf
source_name: ''
source_type: 4
source_version: ''
start_time: 1754408072926
status: 3
tags: []
user_id: Administrador
