artifact_uri: file:///C:/Users/Administrador/Desktop/CaseT%C3%A9cnico_Aquarela_TimeSeries/models/artifacts/759265987466837568/cc8c9d7496214ab69ea629297ed4facd/artifacts
end_time: 1754409265794
entry_point_name: ''
experiment_id: '759265987466837568'
lifecycle_stage: active
run_id: cc8c9d7496214ab69ea629297ed4facd
run_name: Full ML Pipeline Run
run_uuid: cc8c9d7496214ab69ea629297ed4facd
source_name: ''
source_type: 4
source_version: ''
start_time: 1754409243931
status: 3
tags: []
user_id: Administrador
