artifact_uri: file:///C:/Users/Administrador/Desktop/CaseT%C3%A9cnico_Aquarela_TimeSeries/models/artifacts/759265987466837568/fb95429a57c8437898fe96ed30bdab38/artifacts
end_time: 1754406424050
entry_point_name: ''
experiment_id: '759265987466837568'
lifecycle_stage: active
run_id: fb95429a57c8437898fe96ed30bdab38
run_name: Full ML Pipeline Run
run_uuid: fb95429a57c8437898fe96ed30bdab38
source_name: ''
source_type: 4
source_version: ''
start_time: 1754406423753
status: 3
tags: []
user_id: Administrador
